site_name: IoT Health Monitor

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
      default_handler: python


nav:
  - Home: index.md
  - Reference: reference.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
