name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy docs
        run: mkdocs gh-deploy --clean --remote-branch gh-pages --no-history
